### ISSUE TITLE
`ImageRenderer` only renders the first 400 points in a scatter graph

### ISSUE THREAD

**Issue by WaffleLapkin** [yuankunzhang/charming#20]
Reproducer:
```rust
use std::iter;

use charming::{component::Axis, element::AxisType, series::Scatter, Chart, ImageRenderer};

fn main() {
    let c = Chart::new()
        .x_axis(Axis::new().type_(AxisType::Value))
        .y_axis(Axis::new().type_(AxisType::Value))
        .series(
            Scatter::new().data(
                (0..=100)
                    .flat_map(|x| iter::zip(iter::repeat(x), 0..=100))
                    .map(|(x, y)| vec![x, y])
                    .collect(),
            ),
        );

    let mut renderer: ImageRenderer = ImageRenderer::new(1200, 1200);
    renderer.save(&c, format!("/tmp/chc.svg")).unwrap();
}
```
Result:
![a scatter graph with 400 points arranged in 4 100 points tall columns](https://github.com/yuankunzhang/charming/assets/38225716/312585c5-51bc-4107-b3a3-df7176c03f23)

Expected result (a screenshot from html page made by `HtmlRenderer`):

![a scatter graph with 10000 points distributed evenly in x<100, y<100 space](https://github.com/yuankunzhang/charming/assets/38225716/32faaca8-8f8e-43ec-867b-314502813a4b)

**Comment by G2GreenTea** [comment]
I have encountered the same problem. Have you found a solution yet?

**Comment by WaffleLapkin** [comment]
No

**Comment by quentusrex** [comment]
I found a workaround locally. Turns out it's related to progressive rendering being 'broken' for SSR mode. Similar to this filed issue: https://github.com/apache/echarts/issues/18788


I was changing echarts versions(up to 5.5.0) and modifying that source locally and found that disabling progressive by changing to these lines(don't recall the original values currently):
`
      // Configuration for progressive/incremental rendering                                                    
      progressiveThreshold: 0,
      progressive: 0,

`
the system finally printed all of the points. 

What would be helpful would be taking the above reproduction, and then generating a version that can be used to file the issue with echarts, should be able to get this sorted upstream easily.
