### ISSUE TITLE
Shall we have a discord channel?

### ISSUE THREAD

**Issue by bioinformatist** [yuankunzhang/charming#31]
Or other ways for communication?

**Comment by akmere** [comment]
@yuankunzhang 
Please set up 'Discussion' panel if possible here or something, documentation is very nice, I'm completely completely charmed by this library, but because of its novelty there is no place to find answers for potentially stupid questions that would only mess up Issues. Wish you all the best!

**Comment by yuankunzhang** [comment]
@akmere Good advice, thanks!

@bioinformatist I've created a discord channel, please use [this invite](https://discord.gg/VuXzjPPk).
